### ISSUE TITLE
FileUriExposedException in Android N with Camera

### ISSUE THREAD

**Issue by marta-rodriguez** [MLSDev/RxImagePicker#13]
Hi,

I have tried this library in my Nexus 6P with the preview of Android N, and it is working fine with Gallery but when selecting Camera source, it throws a FileUriExposedException.
This is the log:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com/com.mlsdev.rximagepicker.HiddenActivity}: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com/files/20160629_1123251566595922.jpg exposed beyond app through ClipData.Item.getUri()
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2692)
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1445)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6044)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                         Caused by: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com/files/20160629_1123251566595922.jpg exposed beyond app through ClipData.Item.getUri()
                                                                            at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                                                                            at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                                                                            at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
                                                                            at android.content.Intent.prepareToLeaveProcess(Intent.java:8909)
                                                                            at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
                                                                            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
                                                                            at android.app.Activity.startActivityForResult(Activity.java:4223)
                                                                            at android.app.Activity.startActivityForResult(Activity.java:4182)
                                                                            at com.mlsdev.rximagepicker.HiddenActivity.handleIntent(HiddenActivity.java:105)
                                                                            at com.mlsdev.rximagepicker.HiddenActivity.onCreate(HiddenActivity.java:36)
                                                                            at android.app.Activity.performCreate(Activity.java:6658)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2584)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2692) 
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1445) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6044) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```
targetSdkVersion 24

The reason of this error is that file:// uri scheme no more supported because the security is exposed. 
Here you have the google issue: [link](https://code.google.com/p/android/issues/detail?id=203555)

**Comment by Frederikos** [comment]
@marta-rodriguez 
Will check this after release of Android N.

**Comment by Frederikos** [comment]
Apply this fix in 1.1.9

**Comment by marta-rodriguez** [comment]
Great, I'll try, thanks!

**Comment by KaluKhan** [comment]
Step 1. 
Add entry of **Provider** in your menifest file :
`<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>`
Step 2.
 create a **provider_paths.xml** file in xml folder under res folder. Folder may be needed to create if it doesn't exist. The content of the file is shown below. It describes that we would like to share access to the External Storage at root folder (path=".") with the name external_files.
`<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="external_files" path="."/>
</paths>`
Step 3.
The final step is to change the line of code below in
Uri photoURI = Uri.fromFile(createImageFile());
to
Uri photoURI = FileProvider.getUriForFile(context, context.getApplicationContext().getPackageName() + ".my.package.name.provider", createImageFile());
Please refer, full code and solution has been explained [here](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en) .
