### ISSUE TITLE
android.os.FileUriExposedException on API 24 (N)

### ISSUE THREAD

**Issue by Sumsar** [MLSDev/RxImagePicker#19]
https://code.google.com/p/android/issues/detail?id=203555

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{****/com.mlsdev.rximagepicker.HiddenActivity}: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/****/files/20160714_0818461830680327.jpg exposed beyond app through ClipData.Item.getUri()
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2692)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1445)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6044)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/****/files/20160714_0818461830680327.jpg exposed beyond app through ClipData.Item.getUri()
       at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
       at android.net.Uri.checkFileUriExposed(Uri.java:2346)
       at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:8909)
       at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
       at android.app.Activity.startActivityForResult(Activity.java:4223)
       at android.app.Activity.startActivityForResult(Activity.java:4182)
       at com.mlsdev.rximagepicker.HiddenActivity.handleIntent(HiddenActivity.java:105)
       at com.mlsdev.rximagepicker.HiddenActivity.onCreate(HiddenActivity.java:36)
       at android.app.Activity.performCreate(Activity.java:6658)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2584)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2692)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1445)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6044)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by Frederikos** [comment]
Fixed in 1.3.1
