### ISSUE TITLE
Unable to start activity

### ISSUE THREAD

**Issue by bolshakovsashka** [MLSDev/RxImagePicker#30]
On some devices (as Xiaomi, samsung ...), i have this crash

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mlsdev.rximagepicker.HiddenActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT typ=image/* flg=0x41 (has extras) }
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
       at android.app.ActivityThread.access$800(ActivityThread.java:169)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5549)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
Caused by android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT typ=image/* flg=0x41 (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1776)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1496)
       at android.app.Activity.startActivityForResult(Activity.java:3778)
       at android.app.Activity.startActivityForResult(Activity.java:3739)
       at com.mlsdev.rximagepicker.HiddenActivity.handleIntent(HiddenActivity.java:105)
       at com.mlsdev.rximagepicker.HiddenActivity.onCreate(HiddenActivity.java:36)
       at android.app.Activity.performCreate(Activity.java:5975)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
       at android.app.ActivityThread.access$800(ActivityThread.java:169)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5549)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)`

**Comment by angelkoh** [comment]
same bug with LG phone. 
 
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.access$900(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT typ=image/* flg=0x41 (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java)
	at android.app.Activity.startActivityForResult(Activity.java)
	at android.app.Activity.startActivityForResult(Activity.java)
	at com.mlsdev.rximagepicker.HiddenActivity.handleIntent(HiddenActivity.java:113)
	at com.mlsdev.rximagepicker.HiddenActivity.onCreate(HiddenActivity.java:36)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
	at android.app.ActivityThread.access$900(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

**Comment by royabh1** [comment]
Same issue.

**Comment by usc20** [comment]
how to fix it?

**Comment by Frederikos** [comment]
It's a known issue on some Xiaomi devices
https://stackoverflow.com/questions/34021039/action-open-document-not-working-on-miui
You can fork and change ACTION_OPEN_DOCUMENT to ACTION_GET_CONTENT
