### ISSUE TITLE
Cmera capture not working

### ISSUE THREAD

**Issue by sandeshlasnapure** [MLSDev/RxImagePicker#4]
Capture image from camera is not working on samsung s4.

**Comment by Frederikos** [comment]
I don't have Samsung s4.
Can you provide any details, logs?

**Comment by jahangirkabir** [comment]
Capture image is not working in any device !!!

LOG : `E/UncaughtException: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
                                                                                 at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
                                                                                 at android.os.Handler.handleCallback(Handler.java:808)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                 at android.os.Looper.loop(Looper.java:193)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5300)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:646)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                                              Caused by: rx.exceptions.OnErrorNotImplementedException: length=1; index=1
                                                                                 at rx.Observable$27.onError(Observable.java:7535)
                                                                                 at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
                                                                                 at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
                                                                                 at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:239)
                                                                                 at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:774)
                                                                                 at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:532)
                                                                                 at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:521)
                                                                                 at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:808)
                                                                                 at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:197)
                                                                                 at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
                                                                                 at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                 at android.os.Handler.handleCallback(Handler.java:808) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:103) 
                                                                                 at android.os.Looper.loop(Looper.java:193) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5300) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:646) 
                                                                                 at dalvik.system.NativeStart.main(Native Method) 
                                                                              Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
                                                                                 at com.mlsdev.rximagepicker.RxImageConverters$3.call(RxImageConverters.java:76)
                                                                                 at com.mlsdev.rximagepicker.RxImageConverters$3.call(RxImageConverters.java:71)
                                                                                 at rx.Observable.unsafeSubscribe(Observable.java:7710)
                                                                                 at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
                                                                                 at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                 at java.lang.Thread.run(Thread.java:841)`

Code is : RxImagePicker.with(mContext)
                .requestImage(Sources.CAMERA)
                .flatMap(new Func1<Uri, Observable<? extends String>>() {
                    @Override
                    public Observable<? extends String> call(Uri uri) {
                        return RxImageConverters.uriToFullPath(mContext, uri);
                    }
                })
                .subscribe(new Action1<String>() {
                    @Override
                    public void call(String path) {
                        // Do something with your image path
                        // Ex. /storage/emulated/0/DCIM/Camera/20160701_113408.jpg
                        
                    }
                });

**Comment by Frederikos** [comment]
@jahangirkabir 
You receive exception because you don't implement onError method in subscriber.
And RxImageConverters.uriToFullPath is converter for gallery, why u use it when you take image from camera?

Sample code to take picture from camera is on the top of Readme file: 
RxImagePicker.with(context).requestImage(Sources.CAMERA).subscribe(new Action1<Uri>() {
                @Override
                public void call(Uri uri) {
                    //Get image by uri using one of image loading libraries. I use Glide in sample app.
                }
            });
