### ISSUE TITLE
App is crashing when i take picture from gallery 

### ISSUE THREAD

**Issue by askarali** [MLSDev/RxImagePicker#54]
App is crashing when i take picture from gallery  even the same issue occurring  in your sample application . I guess ACTION_OPEN_DOCUMENT is having the issue . if i changed to ACTION_GET_CONTENT it works fine
```

java.lang.NullPointerException: onNext called with null. Null values are generally not allowed in 2.x operators and sources.
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:180)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at com.mlsdev.rximagepicker.RxImagePicker.onImagePicked(RxImagePicker.java:52)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at com.mlsdev.rximagepicker.HiddenActivity.handleGalleryResult(HiddenActivity.java:97)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at com.mlsdev.rximagepicker.HiddenActivity.onActivityResult(HiddenActivity.java:74)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6533)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3935)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3982)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at android.app.ActivityThread.access$1500(ActivityThread.java:180)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:111)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at android.os.Looper.loop(Looper.java:207)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5811)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
12-18 11:37:05.690 20185-20185/parentapp.dt.dtcparent W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
```

**Comment by Frederikos** [comment]
Probably you don't have any app on device that can handle action ACTION_OPEN_DOCUMENT properly.
In new version 2.2.0 you can manually choose if you want to pick image from Gallery or Document.
