### ISSUE TITLE
No Activity found to handle Intent { act=android.media.action.IMAGE_CAPTURE}

### ISSUE THREAD

**Issue by nishantt12** [MLSDev/RxImagePicker#64]
I am getting Activity not found while taking pictures but this issue is appearing only with Samsung mode SM-J737V device. 

this is the full stack trace of the issue: 

Caused by android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 clip={text/uri-list U:content://media/external/images/media/717} (has extras) }
       at android.app.Instrumentation.checkStartActivityResult + 2022(Instrumentation.java:2022)
       at android.app.Instrumentation.execStartActivity + 1677(Instrumentation.java:1677)
       at android.app.Activity.startActivityForResult + 4691(Activity.java:4691)
       at androidx.fragment.app.FragmentActivity.startActivityForResult + 767(FragmentActivity.java:767)
       at androidx.core.app.ActivityCompat.startActivityForResult + 234(ActivityCompat.java:234)
       at androidx.fragment.app.FragmentActivity.onAttachFragment(FragmentActivity.java:8)
       at androidx.fragment.app.FragmentActivity.startActivityFromFragment + 886(FragmentActivity.java:886)
       at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment + 995(FragmentActivity.java:995)
       at androidx.fragment.app.Fragment.startActivityForResult + 1103(Fragment.java:1103)
       at androidx.fragment.app.Fragment.startActivityForResult + 1092(Fragment.java:1092)
       at com.mlsdev.rximagepicker.RxImagePicker.pickImage + 161(RxImagePicker.java:161)
       at com.mlsdev.rximagepicker.RxImagePicker.access$pickImage + 23(RxImagePicker.java:23)
       at com.mlsdev.rximagepicker.RxImagePicker$requestPickImage$1.accept + 125(RxImagePicker.java:125)
       at com.mlsdev.rximagepicker.RxImagePicker$requestPickImage$1.accept + 23(RxImagePicker.java:23)
       at io.reactivex.internal.observers.LambdaObserver.onNext + 63(LambdaObserver.java:63)
       at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext + 311(PublishSubject.java:311)
       at io.reactivex.subjects.PublishSubject.onNext + 231(PublishSubject.java:231)
       at com.mlsdev.rximagepicker.RxImagePicker.onAttach + 76(RxImagePicker.java:76)
       at androidx.fragment.app.FragmentManagerImpl.moveToState + 1404(FragmentManagerImpl.java:1404)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState + 1784(FragmentManagerImpl.java:1784)
       at androidx.fragment.app.FragmentManagerImpl.moveToState + 1852(FragmentManagerImpl.java:1852)
       at androidx.fragment.app.BackStackRecord.executeOps + 802(BackStackRecord.java:802)
       at androidx.fragment.app.FragmentManagerImpl.executeOps + 2625(FragmentManagerImpl.java:2625)
       at androidx.fragment.app.FragmentManagerImpl.transitToStyleIndex(FragmentManagerImpl.java:72)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether + 2411(FragmentManagerImpl.java:2411)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute + 2366(FragmentManagerImpl.java:2366)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions + 2273(FragmentManagerImpl.java:2273)
       at androidx.fragment.app.FragmentManagerImpl$1.run + 733(FragmentManagerImpl.java:733)
       at android.os.Handler.handleCallback + 873(Handler.java:873)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 7156(ActivityThread.java:7156)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main + 975(ZygoteInit.java:975)

**Comment by abedsh** [comment]
Same with Samsung SM-N960N and Android 7.1.2
