### ISSUE TITLE
java.lang.NoClassDefFoundError: rx.subjects.PublishSubject

### ISSUE THREAD

**Issue by chicotutores** [MLSDev/RxImagePicker#9]
I'm getting this error when trying to use on Android 4.1.2 on Samsung DUOS. 
My code:
RxImagePicker.with(getApplicationContext()).requestImage(Sources.CAMERA)
                                .flatMap(new Func1<Uri, Observable<Bitmap>>() {
                                    @Override
                                    public Observable<Bitmap> call(Uri uri) {
                                        return RxImageConverters.uriToBitmap(getApplicationContext(), uri);
                                    }
                                })
                                .subscribe(new Action1<Bitmap>() {
                                    @Override
                                    public void call(Bitmap bitmap) {
                                        ByteArrayOutputStream bos = new ByteArrayOutputStream();
                                        bitmap.compress(Bitmap.CompressFormat.JPEG, 100, bos);
                                        byte[] bitmapData = bos.toByteArray();
                                        encodedPhoto = Base64.encodeToString(bitmapData, Base64.DEFAULT);
                                        imageView.setImageBitmap(bitmap);
                                    }
                                });

LogCat:

06-01 14:00:43.191 27278-27278/br.com.deway.imeeting E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.NoClassDefFoundError: rx.subjects.PublishSubject
                                                                           at com.mlsdev.rximagepicker.RxImagePicker.requestImage(RxImagePicker.java:29)
                                                                           at br.com.deway.imeeting.PortalColaborador.Login.Guardiao.GuardiaoActivity$4.onClick(GuardiaoActivity.java:321)
                                                                           at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:934)
                                                                           at android.widget.AdapterView.performItemClick(AdapterView.java:301)
                                                                           at android.widget.AbsListView.performItemClick(AbsListView.java:1280)
                                                                           at android.widget.AbsListView$PerformClick.run(AbsListView.java:3071)
                                                                           at android.widget.AbsListView$1.run(AbsListView.java:3971)
                                                                           at android.os.Handler.handleCallback(Handler.java:615)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:4960)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by Frederikos** [comment]
Try to run Sample app on your phone and check if it works or not

**Comment by Frederikos** [comment]
Also check this issue https://github.com/MLSDev/RxImagePicker/issues/11
